<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAN8C0j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAN8C0j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZAN8C0j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZAN8C0j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZAN8C0j\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZAN8C0j',
    'container.build_id' => '360a45fb',
    'container.build_time' => 1729191101,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAN8C0j');
